# Generated by Django 5.2 on 2026-08-03 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_alter_staffprofile_allowed_clinical_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('concerns', models.TextField()),
                ('management_treatment', models.TextField(verbose_name='Management/treatment rendered')),
                ('disposition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concern_records', to='core.collegedepartment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concern record',
                'verbose_name_plural': 'Concern records',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
