# Generated by Django 5.2 on 2026-08-03 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_staffprofile_allowed_clinical_modules'),
        ('manage_concern', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concernrecord',
            name='course_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concern_records', to='core.courseprogram'),
        ),
        migrations.AddField(
            model_name='concernrecord',
            name='patient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concernrecord',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concern_records', to='core.yearleveloption'),
        ),
    ]
