# Generated by Django 5.2 on 2026-08-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_staffprofile_allowed_clinical_modules'),
        ('manage_concern', '0002_concernrecord_course_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernrecord',
            name='affiliation_type',
            field=models.CharField(choices=[('catalog', 'Catalog college/department'), ('employee', 'Employee'), ('others', 'Others')], default='catalog', max_length=20),
        ),
        migrations.AddField(
            model_name='concernrecord',
            name='department_other',
            field=models.CharField(blank=True, help_text='Used when affiliation is Others.', max_length=200),
        ),
        migrations.AlterField(
            model_name='concernrecord',
            name='college_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concern_records', to='core.collegedepartment'),
        ),
    ]
