# Generated by Django 5.2 on 2025-08-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related object (appointment, certificate request, etc.)', null=True),
        ),
    ]
