# Generated by Django 5.2.4 on 2025-08-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_add_transaction_type_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profiles/staff/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profiles/students/'),
        ),
    ]
