# Generated by Django 5.2.4 on 2025-08-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_staffprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
