# Generated by Django 5.2.4 on 2025-08-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_staffprofile_allergies_staffprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
