# Generated by Django 5.2.4 on 2025-10-20 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_update_phone_field_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTypeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('followup', 'Follow-up')], help_text='Type of appointment', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this default is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_doctor', models.ForeignKey(blank=True, help_text='Default in-charge doctor for this appointment type', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_appointments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin user who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_type_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Type Default',
                'verbose_name_plural': 'Appointment Type Defaults',
                'ordering': ['appointment_type'],
            },
        ),
    ]
