# Generated by Django 5.2.4 on 2026-01-21 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_staffprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['staff', 'doctor']}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmenttypedefault',
            name='default_doctor',
            field=models.ForeignKey(blank=True, help_text='Default in-charge doctor for this appointment type', limit_choices_to={'role__in': ['staff', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
