# Generated by Django 5.2.4 on 2026-01-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_staffprofile_address_staffprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalexamination',
            name='dental_record',
        ),
        migrations.RemoveField(
            model_name='dentalhealthquestionnaire',
            name='dental_record',
        ),
        migrations.RemoveField(
            model_name='dentalhistory',
            name='dental_record',
        ),
        migrations.RemoveField(
            model_name='dentalrecord',
            name='examined_by',
        ),
        migrations.RemoveField(
            model_name='dentalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pediatricdentalhistory',
            name='dental_record',
        ),
        migrations.RemoveField(
            model_name='dentalsystemsreview',
            name='dental_record',
        ),
        migrations.RemoveField(
            model_name='dentalvitalsigns',
            name='dental_record',
        ),
        migrations.DeleteModel(
            name='DentalChart',
        ),
        migrations.DeleteModel(
            name='DentalExamination',
        ),
        migrations.DeleteModel(
            name='DentalHealthQuestionnaire',
        ),
        migrations.DeleteModel(
            name='DentalHistory',
        ),
        migrations.DeleteModel(
            name='PediatricDentalHistory',
        ),
        migrations.DeleteModel(
            name='DentalSystemsReview',
        ),
        migrations.DeleteModel(
            name='DentalRecord',
        ),
        migrations.DeleteModel(
            name='DentalVitalSigns',
        ),
    ]
