# Generated by Django 5.2 on 2026-05-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_remove_medicalrecord_follow_up_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', help_text='Doctor-documented encounters are saved as completed. Pending is legacy or incomplete data.', max_length=20),
        ),
    ]
