# Generated by Django 5.2 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_alter_medicalrecord_status_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('completed', 'Completed')],
                default='pending',
                help_text='Walk-in records start as pending. Records created when filing an appointment visit are completed.',
                max_length=20,
            ),
        ),
    ]
