# Generated by Django 5.2 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_update_medicalrecord_status_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('completed', 'Completed')],
                default='pending',
                help_text='Completed when saved from the medical record create flows; pending for legacy or incomplete rows.',
                max_length=20,
            ),
        ),
    ]
