# Generated by Django 5.2 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_alter_medicalrecord_status_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('completed', 'Completed')],
                default='pending',
                help_text=(
                    'Pending only while the linked appointment is not yet confirmed. '
                    'Completed when there is prescription or clinical documentation '
                    '(vitals, labs, diagnosis/treatment).'
                ),
                max_length=20,
            ),
        ),
    ]
