# Generated by Django 5.2.4 on 2025-07-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ROLE',
            new_name='role',
        ),
    ]
