# Generated by Django 5.2 on 2026-02-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staffprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table=None,
        ),
    ]
