# Generated by Django 5.2.4 on 2025-07-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_role_user_role'),
    ]

    operations = [
    ]
