# Generated by Django 5.2 on 2026-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_table_alter_staffprofile_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='ptr_no',
            field=models.CharField(blank=True, help_text='Professional Tax Receipt or PTR number', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ptr_no',
            field=models.CharField(blank=True, help_text='Professional Tax Receipt or PTR number', max_length=100),
        ),
    ]
