# Generated by Django 5.2 on 2026-02-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_is_staff_and_sync_models'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
