# Generated by Django 5.2 on 2026-04-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userinvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogram',
            options={'ordering': ['college_department__name', 'name']},
        ),
    ]
