# Generated by Django 5.2 on 2026-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_0013_accountprovisioningaudit_0013_alter_courseprogram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this user is soft-deleted.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp for inactivity cleanup.', null=True),
        ),
        migrations.AlterField(
            model_name='accountprovisioningaudit',
            name='action',
            field=models.CharField(choices=[('created_pending', 'Created (Pending Activation)'), ('created_active', 'Created (Active)'), ('activated', 'Activated'), ('suspended', 'Suspended'), ('soft_deleted', 'Soft Deleted'), ('restored', 'Restored'), ('bulk_activated', 'Bulk Activated'), ('bulk_suspended', 'Bulk Suspended'), ('role_changed', 'Role Changed'), ('password_reset', 'Password Reset')], max_length=30),
        ),
    ]
