# Generated by Django 5.2 on 2026-05-16 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_clinic_and_role_settings(apps, schema_editor):
    ClinicSettings = apps.get_model('core', 'ClinicSettings')
    RoleSettings = apps.get_model('core', 'RoleSettings')

    interval = getattr(settings, 'APPOINTMENT_INTERVAL_MINUTES', 30)
    ClinicSettings.objects.get_or_create(
        pk=1,
        defaults={
            'clinic_name': 'JMCFI Clinic',
            'appointment_interval_minutes': interval,
        },
    )

    role_rows = [
        {
            'role': 'admin',
            'session_timeout_seconds': 43200,
            'profile_required_fields': [
                'first_name', 'last_name', 'staff_id', 'phone',
            ],
            'can_access_analytics': True,
            'can_submit_feedback': False,
            'can_use_messaging': True,
            'can_book_appointments': False,
            'block_clinical_namespaces': True,
            'show_health_tips_nav': False,
        },
        {
            'role': 'doctor',
            'session_timeout_seconds': 86400,
            'profile_required_fields': [
                'first_name', 'last_name', 'staff_id', 'department', 'position',
                'phone', 'license_number', 'ptr_no',
            ],
            'can_access_analytics': True,
            'can_submit_feedback': True,
            'can_use_messaging': True,
            'can_book_appointments': False,
            'block_clinical_namespaces': False,
            'show_health_tips_nav': True,
        },
        {
            'role': 'staff',
            'session_timeout_seconds': 86400,
            'profile_required_fields': [
                'first_name', 'last_name', 'staff_id', 'department', 'phone',
            ],
            'can_access_analytics': True,
            'can_submit_feedback': True,
            'can_use_messaging': True,
            'can_book_appointments': False,
            'block_clinical_namespaces': False,
            'show_health_tips_nav': False,
        },
        {
            'role': 'student',
            'session_timeout_seconds': 86400,
            'profile_required_fields': [
                'first_name', 'last_name', 'student_id', 'middle_name', 'gender',
                'civil_status', 'date_of_birth', 'place_of_birth', 'age', 'address',
                'phone', 'emergency_contact', 'emergency_phone', 'department',
                'blood_type',
            ],
            'can_access_analytics': True,
            'can_submit_feedback': True,
            'can_use_messaging': True,
            'can_book_appointments': True,
            'block_clinical_namespaces': False,
            'show_health_tips_nav': True,
        },
    ]
    for row in role_rows:
        RoleSettings.objects.get_or_create(
            role=row['role'],
            defaults={k: v for k, v in row.items() if k != 'role'},
        )


def unseed_clinic_and_role_settings(apps, schema_editor):
    ClinicSettings = apps.get_model('core', 'ClinicSettings')
    RoleSettings = apps.get_model('core', 'RoleSettings')
    ClinicSettings.objects.filter(pk=1).delete()
    RoleSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('student', 'Student')], max_length=10, unique=True)),
                ('session_timeout_seconds', models.PositiveIntegerField(help_text='Session expiry for this role, in seconds.')),
                ('profile_required_fields', models.JSONField(default=list, help_text='Field names required before profile is considered complete.')),
                ('can_access_analytics', models.BooleanField(default=True)),
                ('can_submit_feedback', models.BooleanField(default=True)),
                ('can_use_messaging', models.BooleanField(default=True)),
                ('can_book_appointments', models.BooleanField(default=False)),
                ('block_clinical_namespaces', models.BooleanField(default=False, help_text='When true, admin users cannot access clinical app namespaces.')),
                ('show_health_tips_nav', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role settings',
                'verbose_name_plural': 'Role settings',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='JMCFI Clinic', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=64)),
                ('date_format', models.CharField(default='Y-m-d', help_text='Python strftime-style date format for exports and displays.', max_length=20)),
                ('google_allowed_domains', models.TextField(blank=True, default='', help_text='Comma-separated email domains allowed for Google sign-in. Empty uses env GOOGLE_ALLOWED_DOMAINS.')),
                ('allow_student_self_signup', models.BooleanField(default=True, help_text='Allow new students to register via Google OAuth.')),
                ('default_session_hours', models.PositiveSmallIntegerField(default=24, help_text='Fallback session length when role settings are unavailable.')),
                ('appointment_interval_minutes', models.PositiveSmallIntegerField(default=30, help_text='Minimum buffer between consecutive appointments.')),
                ('max_advance_booking_days', models.PositiveSmallIntegerField(default=30, help_text='How far ahead students may book appointments.')),
                ('cancellation_cutoff_hours', models.PositiveSmallIntegerField(default=24, help_text='Hours before appointment when cancellation is no longer allowed.')),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('digest_hour', models.PositiveSmallIntegerField(default=8, help_text='Hour of day (0–23) for notification digests when enabled.')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic settings',
                'verbose_name_plural': 'Clinic settings',
            },
        ),
        migrations.RunPython(seed_clinic_and_role_settings, unseed_clinic_and_role_settings),
    ]
