# Generated by Django 5.2 on 2026-05-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('clinic', 'Clinic'), ('role', 'Role')], max_length=10)),
                ('role', models.CharField(blank=True, default='', help_text='Role key when setting_type is role.', max_length=10)),
                ('field_name', models.CharField(max_length=80)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings change log',
                'verbose_name_plural': 'Settings change logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
