# Generated by Django 5.2 on 2026-05-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_student_to_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='max_advance_booking_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='How far ahead patients may book appointments.'),
        ),
    ]
