# Generated by Django 5.2 on 2026-05-31 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_clinicsettings_max_advance_booking_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export')], max_length=10)),
                ('resource_type', models.CharField(choices=[('medical_record', 'Medical Record'), ('dental_record', 'Dental Record')], max_length=20)),
                ('resource_id', models.PositiveIntegerField()),
                ('resource_label', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_access_actions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical access log',
                'verbose_name_plural': 'Clinical access logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='core_clinic_patient_ee36e4_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_clinic_resourc_d30802_idx'), models.Index(fields=['actor', '-created_at'], name='core_clinic_actor_i_78befc_idx')],
            },
        ),
    ]
