# Generated by Django 5.2 on 2026-06-01 02:24

from django.db import migrations, models

IBED_COURSE_OPTIONAL = (
    'IBED - Primary',
    'IBED - Junior High School',
    'IBED - Junior Highschool',
)


def set_ibed_course_optional(apps, schema_editor):
    CollegeDepartment = apps.get_model('core', 'CollegeDepartment')
    CollegeDepartment.objects.filter(name__in=IBED_COURSE_OPTIONAL).update(course_optional=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clinicalaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedepartment',
            name='course_optional',
            field=models.BooleanField(default=False, help_text='When true, Course/Program is not required for this college.'),
        ),
        migrations.RunPython(set_ibed_course_optional, migrations.RunPython.noop),
    ]
