# Generated by Django 5.2 on 2026-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_staff_contact_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
