# Generated by Django 5.2 on 2026-06-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_patientprofile_citizenship_patientprofile_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
