# Generated by Django 5.2 on 2026-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_patientprofile_position_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patient_category',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('guest', 'Guest')], default='student', help_text='Student, employee, or guest — controls academic/institutional fields.', max_length=20),
        ),
    ]
