# Generated by Django 5.2

from django.db import migrations, models


def forwards_guest_to_walk_in(apps, schema_editor):
    PatientProfile = apps.get_model('core', 'PatientProfile')
    PatientProfile.objects.filter(patient_category='guest').update(patient_category='walk_in')


def backwards_walk_in_to_guest(apps, schema_editor):
    PatientProfile = apps.get_model('core', 'PatientProfile')
    PatientProfile.objects.filter(patient_category='walk_in').update(patient_category='guest')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_patient_category_and_guest_designation'),
    ]

    operations = [
        migrations.RunPython(forwards_guest_to_walk_in, backwards_walk_in_to_guest),
        migrations.AlterField(
            model_name='patientprofile',
            name='patient_category',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                    ('walk_in', 'Walk-in'),
                ],
                default='student',
                help_text='Student, employee, or walk-in — controls academic/institutional fields.',
                max_length=20,
            ),
        ),
    ]
