# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_guest_to_walk_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_category',
        ),
    ]
