# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_patient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_employee',
            field=models.BooleanField(
                default=False,
                help_text='If true, only College/Department is required for academic info.',
            ),
        ),
    ]
