# Generated by Django 5.2 on 2026-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_patientprofile_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='allowed_clinical_modules',
            field=models.JSONField(blank=True, default=list, help_text='Doctor-only: granted service/health-form module keys. Empty = none.'),
        ),
    ]
