# Generated by Django 5.2 on 2026-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_staffprofile_allowed_clinical_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='allowed_clinical_modules',
            field=models.JSONField(blank=True, default=list, help_text='Doctor/staff: granted service/health-form module keys. Empty = none.'),
        ),
    ]
