# Generated by Django 5.2 on 2026-08-10 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_staffprofile_allowed_clinical_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Real contact email for walk-in guests (not used for login).', max_length=254),
        ),
        migrations.CreateModel(
            name='GuestAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('appointment', 'Appointment'), ('health_form', 'Health Form')], max_length=32)),
                ('object_id', models.PositiveIntegerField()),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guest_access_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'object_id'], name='core_guesta_user_id_e57b30_idx')],
            },
        ),
    ]
