# Generated by Django 5.2 on 2026-08-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_migrate_walkin_emails_to_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_completed', 'Appointment Completed'), ('appointment_scheduled', 'New Appointment Scheduled'), ('certificate_requested', 'Certificate Request Submitted'), ('certificate_approved', 'Certificate Request Approved'), ('certificate_ready', 'Certificate Ready for Collection'), ('certificate_rejected', 'Certificate Request Rejected'), ('certificate_processing', 'Certificate Being Processed'), ('health_tip_new', 'New Health Tip Available'), ('health_tip_updated', 'Health Tip Updated'), ('medical_record_created', 'Medical Record Created'), ('medical_record_updated', 'Medical Record Updated'), ('health_form_incomplete', 'Health Form Incomplete'), ('system_maintenance', 'System Maintenance'), ('general_announcement', 'General Announcement'), ('feedback_request', 'Feedback Request'), ('direct_message', 'Direct Message'), ('announcement_posted', 'Announcement Posted')], help_text='Specific transaction type for better routing', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Real contact email for guest patients (not used for login).', max_length=254),
        ),
    ]
