# Generated by Django 5.2 on 2026-01-26 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cleanliness_rating',
            field=models.IntegerField(blank=True, help_text='Rate facility cleanliness', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General Feedback'), ('appointment', 'Appointment Experience'), ('staff', 'Staff Service'), ('facility', 'Facility & Cleanliness'), ('wait_time', 'Wait Time'), ('treatment', 'Treatment Quality'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='staff_rating',
            field=models.IntegerField(blank=True, help_text='Rate staff friendliness and professionalism', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='wait_time_rating',
            field=models.IntegerField(blank=True, help_text='Rate wait time satisfaction', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='would_recommend',
            field=models.BooleanField(default=True, help_text='Would you recommend our clinic?'),
        ),
    ]
