# Generated by Django 5.2 on 2026-03-09 08:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit in PHP', max_digits=10)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, default='', max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('tube', 'Tube'), ('sachet', 'Sachet'), ('piece', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('ml', 'Milliliter (mL)'), ('mg', 'Milligram (mg)'), ('roll', 'Roll'), ('pair', 'Pair'), ('set', 'Set')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, default='', help_text='e.g., 500mg, 250mg/5ml', max_length=50)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this quantity')),
                ('max_stock_level', models.PositiveIntegerField(default=500, help_text='Alert when stock exceeds this quantity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('prescription_reference', models.CharField(blank=True, default='', help_text='Doctor prescription or medical record reference', max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensings', to='pharmacy.batch')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_dispensed_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_dispensings', to=settings.AUTH_USER_MODEL)),
                ('prescribing_doctor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['staff', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('stock_in', 'Stock In (PO Received)'), ('dispensed', 'Dispensed'), ('adjustment', 'Stock Adjustment'), ('expired_disposed', 'Expired / Disposed'), ('order_created', 'Purchase Order Created'), ('order_approved', 'Purchase Order Approved'), ('order_received', 'Purchase Order Received')], max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pharmacy.batch')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.medicinecategory'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='pharmacy.supplier')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit in PHP', max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pharmacy.medicine')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Positive to add, negative to deduct')),
                ('reason', models.CharField(choices=[('expired', 'Expired – Disposed'), ('damaged', 'Damaged / Broken'), ('correction', 'Inventory Correction'), ('returned', 'Returned to Supplier'), ('donated', 'Donated'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_adjustments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pharmacy.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('medicine', 'batch_number')},
        ),
    ]
