# Generated by Django 5.2 on 2026-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('stock_in', 'Stock In (PO Received)'), ('dispensed', 'Dispensed'), ('adjustment', 'Stock Adjustment'), ('expired_disposed', 'Expired / Disposed'), ('medicine_added', 'Medicine Added'), ('order_created', 'Purchase Order Created'), ('order_approved', 'Purchase Order Approved'), ('order_received', 'Purchase Order Received')], max_length=30),
        ),
    ]
