# Generated by Django 5.2 on 2026-05-20 11:10

from django.conf import settings
from django.db import migrations, models


def seed_purchase_order_counter(apps, schema_editor):
    PurchaseOrder = apps.get_model('pharmacy', 'PurchaseOrder')
    PharmacyCounter = apps.get_model('pharmacy', 'PharmacyCounter')
    max_seq = 0
    for po in PurchaseOrder.objects.only('order_number', 'pk'):
        max_seq = max(max_seq, po.pk)
        if po.order_number and '-' in po.order_number:
            suffix = po.order_number.rsplit('-', 1)[-1]
            try:
                max_seq = max(max_seq, int(suffix))
            except ValueError:
                pass
    PharmacyCounter.objects.update_or_create(
        pk=1,
        defaults={'next_purchase_order_seq': max_seq},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacy_phase1_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_purchase_order_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pharmacy counter',
                'verbose_name_plural': 'Pharmacy counters',
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='pharm_batch_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dispensing',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='pharm_disp_qty_min'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gte', 1)), name='pharm_poitem_qty_ordered_min'),
        ),
        migrations.RunPython(seed_purchase_order_counter, migrations.RunPython.noop),
    ]
