# Generated by Django 5.2 on 2026-05-20 13:29

from django.db import migrations, models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.utils import timezone


def backfill_medicine_stock_cache(apps, schema_editor):
    Medicine = apps.get_model('pharmacy', 'Medicine')
    Batch = apps.get_model('pharmacy', 'Batch')
    today = timezone.now().date()
    now = timezone.now()
    for med in Medicine.objects.all().only('pk'):
        total = Batch.objects.filter(
            medicine_id=med.pk,
            quantity__gt=0,
            expiry_date__gt=today,
        ).aggregate(total=Coalesce(Sum('quantity'), 0))['total']
        Medicine.objects.filter(pk=med.pk).update(
            cached_non_expired_stock=int(total or 0),
            stock_cache_updated_at=now,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_phase3_data_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='cached_non_expired_stock',
            field=models.PositiveIntegerField(default=0, help_text='Cached sum of non-expired batch qty; refreshed on batch changes.'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_cache_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active', 'cached_non_expired_stock'], name='pharm_med_active_stock_idx'),
        ),
        migrations.RunPython(backfill_medicine_stock_cache, migrations.RunPython.noop),
    ]
