# Generated by Django 5.2 on 2026-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecord',
            name='designation',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('guest', 'Guest')], max_length=20),
        ),
    ]
