# Generated by Django 5.2.4 on 2026-02-05 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0002_dentalrecord_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalchart',
            name='condition',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('decayed', 'Decayed/Caries'), ('filled', 'Filled'), ('missing', 'Missing'), ('extracted', 'Extracted'), ('impacted', 'Impacted'), ('root_canal', 'Root Canal'), ('crowned', 'Crowned'), ('bridge', 'Bridge'), ('bridge_pontic', 'Bridge Pontic'), ('implant', 'Implant'), ('fractured', 'Fractured'), ('unerupted', 'Unerupted'), ('partially_erupted', 'Partially Erupted'), ('sealant', 'Sealant'), ('veneer', 'Veneer'), ('temporary', 'Temporary Filling'), ('root_fragment', 'Root Fragment'), ('anomaly', 'Anomaly'), ('other', 'Other')], default='healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='dentalchart',
            name='tooth_number',
            field=models.PositiveIntegerField(help_text='FDI notation: 11-18 (UR), 21-28 (UL), 31-38 (LL), 41-48 (LR) for permanent; 51-55 (UR), 61-65 (UL), 71-75 (LL), 81-85 (LR) for primary'),
        ),
        migrations.CreateModel(
            name='DentalChartSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this snapshot')),
                ('chart_data', models.JSONField(help_text='JSON snapshot of all teeth and surfaces')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_snapshots', to='dental_records.dentalrecord')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ToothSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('mesial', 'Mesial (M)'), ('distal', 'Distal (D)'), ('buccal', 'Buccal/Facial (B/F)'), ('lingual', 'Lingual/Palatal (L/P)'), ('occlusal', 'Occlusal (O)'), ('incisal', 'Incisal (I)')], max_length=20)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('decayed', 'Decayed/Caries'), ('filled', 'Filled'), ('filled_with_caries', 'Filled with Caries'), ('sealant', 'Sealant'), ('fracture', 'Fracture'), ('erosion', 'Erosion'), ('abrasion', 'Abrasion'), ('attrition', 'Attrition'), ('demineralization', 'Demineralization')], default='healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='dental_records.dentalchart')),
            ],
            options={
                'ordering': ['surface'],
                'unique_together': {('tooth', 'surface')},
            },
        ),
    ]
