# Generated by Django 5.2

from django.db import migrations, models


def forwards_guest_to_walk_in(apps, schema_editor):
    DentalRecord = apps.get_model('dental_records', 'DentalRecord')
    DentalRecord.objects.filter(designation='guest').update(designation='walk_in')


def backwards_walk_in_to_guest(apps, schema_editor):
    DentalRecord = apps.get_model('dental_records', 'DentalRecord')
    DentalRecord.objects.filter(designation='walk_in').update(designation='guest')


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0002_patient_category_and_guest_designation'),
    ]

    operations = [
        migrations.RunPython(forwards_guest_to_walk_in, backwards_walk_in_to_guest),
        migrations.AlterField(
            model_name='dentalrecord',
            name='designation',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                    ('walk_in', 'Walk-in'),
                ],
                max_length=20,
            ),
        ),
    ]
