# Generated by Django 5.2.4 on 2026-02-06 06:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0003_add_fdi_surfaces_and_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='informed_consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='informed_consent_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('procedure_done', models.TextField(help_text='Description of the procedure performed')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='dental_records.dentalrecord')),
                ('dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
