# Generated by Django 5.2

from django.db import migrations, models


def forwards_map_walk_in_to_student(apps, schema_editor):
    DentalRecord = apps.get_model('dental_records', 'DentalRecord')
    DentalRecord.objects.filter(designation__in=['guest', 'walk_in']).update(designation='student')


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0003_rename_guest_to_walk_in'),
    ]

    operations = [
        migrations.RunPython(forwards_map_walk_in_to_student, backwards_noop),
        migrations.AlterField(
            model_name='dentalrecord',
            name='designation',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                ],
                max_length=20,
            ),
        ),
    ]
