# Generated by Django 5.2 on 2026-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0004_remove_walk_in_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='year_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
