# Generated by Django 5.2.4 on 2026-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_records', '0004_dentalrecord_informed_consent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
