# Generated by Django 5.2.4 on 2026-01-26 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('followup', 'Follow-up')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['staff', 'doctor']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'management_appointment',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentTypeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('followup', 'Follow-up')], help_text='Type of appointment', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this default is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_doctor', models.ForeignKey(blank=True, help_text='Default in-charge doctor for this appointment type', limit_choices_to={'role__in': ['staff', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_type_defaults', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin user who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_type_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Type Default',
                'verbose_name_plural': 'Appointment Type Defaults',
                'db_table': 'management_appointmenttypedefault',
                'ordering': ['appointment_type'],
            },
        ),
    ]
