# Generated by Django 5.2 on 2026-02-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='appointmenttypedefault',
            table=None,
        ),
    ]
