# Generated by Django 5.2 on 2026-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('followup', 'Follow-up'), ('dental', 'Dental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmenttypedefault',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('followup', 'Follow-up'), ('dental', 'Dental')], help_text='Type of appointment', max_length=20, unique=True),
        ),
    ]
