# Generated by Django 5.2 on 2026-03-08 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttypedefault',
            name='assigned_doctors',
            field=models.ManyToManyField(blank=True, help_text='Doctors allowed for this appointment type. If empty, all staff/doctors are available.', limit_choices_to={'role__in': ['staff', 'doctor']}, related_name='assigned_appointment_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
