# Generated by Django 5.2 on 2026-03-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_assigned_doctors_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttypedefault',
            name='default_doctor',
        ),
    ]
