# Generated by Django 5.2 on 2026-05-13 14:30

from django.db import migrations


def create_default_appointment_types(apps, schema_editor):
    """Create default AppointmentTypeDefault records for all 6 appointment types."""
    AppointmentTypeDefault = apps.get_model('appointments', 'AppointmentTypeDefault')
    
    appointment_types = [
        'consultation',
        'checkup',
        'vaccination',
        'emergency',
        'followup',
        'dental',
    ]
    
    for type_key in appointment_types:
        # Only create if it doesn't already exist
        AppointmentTypeDefault.objects.get_or_create(appointment_type=type_key)


def reverse_create_default_appointment_types(apps, schema_editor):
    """Delete the auto-created AppointmentTypeDefault records."""
    AppointmentTypeDefault = apps.get_model('appointments', 'AppointmentTypeDefault')
    
    appointment_types = [
        'consultation',
        'checkup',
        'vaccination',
        'emergency',
        'followup',
        'dental',
    ]
    
    for type_key in appointment_types:
        AppointmentTypeDefault.objects.filter(appointment_type=type_key).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_default_doctor'),
    ]

    operations = [
        migrations.RunPython(create_default_appointment_types, reverse_create_default_appointment_types),
    ]
