# Generated by Django 5.2 on 2026-05-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_followup_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('dental', 'Dental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmenttypedefault',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'General Consultation'), ('checkup', 'Health Checkup'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('dental', 'Dental')], help_text='Type of appointment', max_length=20, unique=True),
        ),
    ]
