# Generated by Django 5.2 on 2026-08-04 12:48

import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.drive_upload_to)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_items', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'kind': 'folder'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.driveitem')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['parent', 'trashed_at'], name='files_drive_parent__48c070_idx'), models.Index(fields=['owner', 'name'], name='files_drive_owner_i_001d9f_idx'), models.Index(fields=['name'], name='files_drive_name_cdcae9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('trashed_at__isnull', True)), fields=('parent', 'name'), name='unique_drive_name_per_parent_active', nulls_distinct=False)],
            },
        ),
    ]
