# Generated by Django 5.2 on 2026-08-04 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial_drive_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driveitem',
            name='unique_drive_name_per_parent_active',
        ),
        migrations.AddConstraint(
            model_name='driveitem',
            constraint=models.UniqueConstraint(condition=models.Q(('trashed_at__isnull', True)), fields=('parent', 'name'), name='unique_drive_name_per_parent_active'),
        ),
    ]
