# Generated by Django 5.2 on 2026-03-18 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deduplicate_pending_requests(apps, schema_editor):
    DocumentRequest = apps.get_model('document_request', 'DocumentRequest')
    db_alias = schema_editor.connection.alias

    duplicate_groups = (
        DocumentRequest.objects.using(db_alias)
        .filter(status='pending')
        .values('student_id', 'document_type')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )

    for group in duplicate_groups:
        duplicates = list(
            DocumentRequest.objects.using(db_alias)
            .filter(
                student_id=group['student_id'],
                document_type=group['document_type'],
                status='pending',
            )
            .order_by('-created_at', '-id')
        )

        # Keep the newest pending request, soft-close the rest.
        for stale_request in duplicates[1:]:
            stale_request.status = 'rejected'
            stale_request.rejection_reason = (
                stale_request.rejection_reason
                or 'Auto-closed during migration to remove duplicate pending requests.'
            )
            stale_request.save(update_fields=['status', 'rejection_reason', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0001_initial'),
        ('health_forms_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_days', models.JSONField(default=list, help_text='List of day codes (mon..sun) when requests are allowed.')),
                ('start_time', models.TimeField(help_text='Allowed request window start time.')),
                ('end_time', models.TimeField(help_text='Allowed request window end time.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Request Schedule',
                'verbose_name_plural': 'Student Request Schedules',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who created the request (student self-request or doctor/admin on behalf).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='request_origin',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor/Admin')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='scheduled_for_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='scheduled_for_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('medical_certificate', 'Medical Certificate'), ('medical_record', 'Medical Record'), ('dental_record', 'Dental Record')], default='medical_certificate', max_length=30),
        ),
        migrations.RunPython(deduplicate_pending_requests, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='documentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'document_type'), name='uniq_pending_document_request_per_type'),
        ),
        migrations.AddField(
            model_name='studentrequestschedule',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='record_request_schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrequestschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_record_request_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
