# Generated by Django 5.2 on 2026-02-10 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0001_initial'),
        ('health_forms_services', '0010_medicalcertificate_prescription_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='medical_certificate',
            field=models.ForeignKey(blank=True, help_text='Linked medical certificate from Health Services', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='health_forms_services.medicalcertificate'),
        ),
    ]
