# Generated by Django 5.2 on 2026-04-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_default_doctor'),
        ('document_request', '0002_studentrequestschedule_documentrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Appointment linked to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='appointments.appointment'),
        ),
    ]
