# Generated by Django 5.2 on 2026-02-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0002_documentrequest_medical_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('medical_certificate', 'Medical Certificate')], default='medical_certificate', max_length=30),
        ),
    ]
