# Generated by Django 5.2 on 2026-04-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0003_documentrequest_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='appointment',
        ),
    ]
