# Generated by Django 5.2 on 2026-02-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0003_alter_documentrequest_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
