# Generated by Django 5.2 on 2026-04-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0004_remove_documentrequest_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRequestSchedule',
        ),
    ]
