# Generated by Django 5.2 on 2026-04-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0005_delete_studentrequestschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='scheduled_for_date',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='scheduled_for_time',
        ),
    ]
