# Generated by Django 5.2 on 2026-05-16 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_migrate_statuses_and_links(apps, schema_editor):
    DocumentRequest = apps.get_model('document_request', 'DocumentRequest')
    MedicalCertificate = apps.get_model('document_request', 'MedicalCertificate')

    DocumentRequest.objects.filter(status='pending').update(status='pending_review')
    DocumentRequest.objects.filter(status='completed').update(status='ready_for_pickup')

    MedicalCertificate.objects.filter(status='pending').update(status='draft')
    MedicalCertificate.objects.filter(status='completed').update(status='issued')
    MedicalCertificate.objects.filter(status='rejected').update(status='void')

    for doc_request in DocumentRequest.objects.exclude(medical_certificate_id=None).iterator():
        MedicalCertificate.objects.filter(pk=doc_request.medical_certificate_id).update(
            document_request_id=doc_request.pk,
        )


def backwards_migrate_statuses_and_links(apps, schema_editor):
    DocumentRequest = apps.get_model('document_request', 'DocumentRequest')
    MedicalCertificate = apps.get_model('document_request', 'MedicalCertificate')

    DocumentRequest.objects.filter(status='pending_review').update(status='pending')
    DocumentRequest.objects.filter(status='ready_for_pickup').update(status='completed')

    MedicalCertificate.objects.filter(status='draft').update(status='pending')
    MedicalCertificate.objects.filter(status='issued').update(status='completed')
    MedicalCertificate.objects.filter(status='void').update(status='rejected')

    MedicalCertificate.objects.all().update(document_request_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0007_move_medical_certificate_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentrequest',
            name='uniq_pending_document_request_per_type',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                help_text='Primary clinician notified for this request.',
                limit_choices_to={'role__in': ['doctor', 'staff']},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_document_requests',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='document_request',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='certificate',
                to='document_request.documentrequest',
            ),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='issued_pdf',
            field=models.FileField(blank=True, upload_to='certificates/issued/'),
        ),
        migrations.RunPython(forwards_migrate_statuses_and_links, backwards_migrate_statuses_and_links),
        migrations.AlterField(
            model_name='documentrequest',
            name='medical_certificate',
            field=models.ForeignKey(
                blank=True,
                help_text='Linked medical certificate (legacy FK; prefer certificate.document_request).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_document_requests',
                to='document_request.medicalcertificate',
            ),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_review', 'Pending review'),
                    ('ready_for_pickup', 'Ready for pickup'),
                    ('rejected', 'Rejected'),
                ],
                default='pending_review',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='status',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('issued', 'Issued'), ('void', 'Void')],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='documentrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'pending_review')),
                fields=('student', 'document_type'),
                name='uniq_pending_document_request_per_type',
            ),
        ),
        migrations.RenameModel(
            old_name='DoctorSignature',
            new_name='ClinicianSignature',
        ),
        migrations.CreateModel(
            name='DocumentRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('created', 'Created'),
                            ('certificate_saved', 'Certificate saved'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                        ],
                        max_length=50,
                    ),
                ),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='document_request_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='document_request.documentrequest',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Document Request Event',
                'verbose_name_plural': 'Document Request Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
