# Generated by Django 5.2 on 2026-05-16 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0008_architecture_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniciansignature',
            options={'ordering': ['doctor__last_name', 'doctor__first_name'], 'verbose_name': 'Clinician Signature', 'verbose_name_plural': 'Clinician Signatures'},
        ),
        migrations.AlterField(
            model_name='cliniciansignature',
            name='doctor',
            field=models.OneToOneField(limit_choices_to={'role__in': ['doctor', 'staff', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_signature', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliniciansignature',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinician_signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
