# Generated by Django 5.2.4 on 2026-01-26 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('form_file', models.FileField(blank=True, null=True, upload_to='health_forms/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('permanent_address', models.TextField(blank=True)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('current_address', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20)),
                ('department_college_office', models.CharField(blank=True, max_length=200)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_contact', models.CharField(blank=True, max_length=20)),
                ('immunization_records', models.JSONField(blank=True, default=dict)),
                ('illness_history', models.JSONField(blank=True, default=list)),
                ('allergies', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('menarche_age', models.PositiveIntegerField(blank=True, null=True)),
                ('menstrual_duration', models.CharField(blank=True, max_length=50)),
                ('menstrual_interval', models.CharField(blank=True, max_length=50)),
                ('menstrual_amount', models.CharField(blank=True, max_length=50)),
                ('menstrual_symptoms', models.TextField(blank=True)),
                ('obstetric_history', models.TextField(blank=True)),
                ('present_illness', models.TextField(blank=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi_remarks', models.CharField(blank=True, max_length=50)),
                ('physical_exam_findings', models.JSONField(blank=True, default=dict)),
                ('other_findings', models.TextField(blank=True)),
                ('diagnostic_tests', models.JSONField(blank=True, default=dict)),
                ('physician_impression', models.TextField(blank=True)),
                ('final_remarks', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('examining_physician', models.CharField(blank=True, max_length=200)),
                ('examination_date', models.DateField(blank=True, null=True)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('processing_notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_health_forms', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Profile Form',
                'verbose_name_plural': 'Health Profile Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('extract', 'Data Extraction'), ('validate', 'Validation'), ('review', 'Manual Review'), ('approve', 'Approved'), ('reject', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='health_forms_services.healthprofileform')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
