# Generated by Django 5.2 on 2026-01-26 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofileform',
            name='extraction_confidence',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='form_file',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='processing_notes',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='raw_extracted_data',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='validation_flags',
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_health_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='FormProcessingLog',
        ),
    ]
