# Generated by Django 5.2 on 2026-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0002_remove_moved_medical_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofileform',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='institution_id',
            field=models.CharField(blank=True, help_text='Student ID or Staff ID', max_length=30),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='ptr_no',
            field=models.CharField(blank=True, help_text='Professional Tax Receipt or PTR number', max_length=100),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='year_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff'), ('doctor', 'Doctor'), ('employee', 'Employee')], max_length=20),
        ),
    ]
