# Generated by Django 5.2.4 on 2026-01-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0002_remove_ai_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofileform',
            old_name='other_findings',
            new_name='test_anti_hbs_titer_findings',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='diagnostic_tests',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='illness_history',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='immunization_records',
        ),
        migrations.RemoveField(
            model_name='healthprofileform',
            name='physical_exam_findings',
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_abdomen',
            field=models.TextField(blank=True, help_text='Abdomen findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_chest_lungs',
            field=models.TextField(blank=True, help_text='Chest and lungs findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_extremities',
            field=models.TextField(blank=True, help_text='Extremities findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_general',
            field=models.TextField(blank=True, help_text='General examination findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_genitourinary',
            field=models.TextField(blank=True, help_text='Genitourinary findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_heent',
            field=models.TextField(blank=True, help_text='Head, Eyes, Ears, Nose, Throat findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_neurologic',
            field=models.TextField(blank=True, help_text='Neurologic findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='exam_other_findings',
            field=models.TextField(blank=True, help_text='Other significant findings'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_chickenpox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_measles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_mumps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_others',
            field=models.TextField(blank=True, help_text='Other illnesses/conditions'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_ptb_pki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='illness_rubella',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_bcg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_bcg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_covid19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_covid19_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_dpt_tetanus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_dpt_tetanus_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_hepatitis_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_hepatitis_b_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_hib',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_hib_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_influenza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_influenza_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_measles_mmr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_measles_mmr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_others',
            field=models.TextField(blank=True, help_text='Other immunizations'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_pneumonia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_pneumonia_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_polio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_polio_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_rotavirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='immunization_rotavirus_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_anti_hbs_titer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_anti_hbs_titer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_cbc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_cbc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_cbc_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_chest_xray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_chest_xray_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_chest_xray_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_drug_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_drug_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_drug_test_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_fecalysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_fecalysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_fecalysis_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_hbsag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_hbsag_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_hbsag_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_others',
            field=models.TextField(blank=True, help_text='Other diagnostic tests'),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_psychological',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_psychological_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_psychological_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_urinalysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_urinalysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofileform',
            name='test_urinalysis_findings',
            field=models.TextField(blank=True),
        ),
    ]
