# Generated by Django 5.2 on 2026-05-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0003_healthprofileform_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalhealthform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dentalservicesrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientchart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
    ]
