# Generated by Django 5.2.4 on 2026-01-27 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0003_rename_other_findings_healthprofileform_test_anti_hbs_titer_findings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofileform',
            name='examining_physician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_health_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
