# Generated by Django 5.2 on 2026-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0004_alter_dentalhealthform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20),
        ),
    ]
