# Generated by Django 5.2 on 2026-05-09 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0005_alter_prescription_status'),
        ('medical_records', '0003_remove_medicalrecord_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_record', to='medical_records.medicalrecord'),
        ),
    ]
