# Generated by Django 5.2 on 2026-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0007_backfill_prescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalhealthform',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Patient'), ('employee', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Patient'), ('staff', 'Staff'), ('doctor', 'Doctor'), ('employee', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientchart',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Patient'), ('employee', 'Employee')], max_length=20),
        ),
    ]
