# Generated by Django 5.2.4 on 2026-02-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0007_rename_buccal_mucosa_dentalhealthform_current_treatment_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentalhealthform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dental Records Form', 'verbose_name_plural': 'Dental Records Forms'},
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='currently_undergoing_treatment',
            new_name='cond_caries_free',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='endodontics_anterior',
            new_name='cond_for_endodontic',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='endodontics_posterior',
            new_name='cond_for_orthodontic',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_class_i',
            new_name='cond_for_sealant',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_class_ii',
            new_name='cond_gingival_inflammation',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_class_iii',
            new_name='cond_indicated_extraction',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_class_iv',
            new_name='cond_indicated_restoration',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_class_v',
            new_name='cond_needs_oral_prophylaxis',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_class_vi',
            new_name='cond_needs_prosthesis',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='operative_onlay_inlay',
            new_name='cond_no_treatment_needed',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='pediatric_fluoride',
            new_name='cond_others',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='current_treatment_details',
            new_name='cond_others_detail',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='pediatric_pulpotomy',
            new_name='cond_poor_oral_hygiene',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='dentist_date',
            new_name='date_of_examination',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='endodontics_anterior_details',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='pediatric_sealant',
            new_name='inflammation_of_gingiva',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='endodontics_posterior_details',
            new_name='place_of_birth',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='pediatric_space_maintainer',
            new_name='presence_of_calculus',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='pediatric_ssc',
            new_name='presence_of_debris',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='periodontics_oral_prophylaxis',
            new_name='tmj_deviation',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='periodontics_scaling_root_planning',
            new_name='tmj_pain',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='prosthodontics_complete_denture',
            new_name='tmj_popping',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='prosthodontics_fpd',
            new_name='tmj_tooth_wear',
        ),
        migrations.RenameField(
            model_name='dentalhealthform',
            old_name='prosthodontics_rpd',
            new_name='under_orthodontic_treatment',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_class_i_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_class_ii_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_class_iii_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_class_iv_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_class_v_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_class_vi_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='operative_onlay_inlay_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='pediatric_pulpotomy_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='pediatric_sealant_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='pediatric_space_maintainer_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='pediatric_ssc_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='prosthodontics_fpd_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='prosthodontics_rpd_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='prosthodontics_single_crown',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='prosthodontics_single_crown_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='prosthodontics_veneers_laminates',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='prosthodontics_veneers_laminates_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_odontectomy',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_odontectomy_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_operculectomy',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_operculectomy_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_other_pathological',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_other_pathological_details',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_tooth_extraction',
        ),
        migrations.RemoveField(
            model_name='dentalhealthform',
            name='surgery_tooth_extraction_details',
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='caries_free_teeth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='decayed_teeth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='dentofacial_anomaly',
            field=models.TextField(blank=True, help_text='Dentofacial Anomaly, Neoplasm, Others'),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='filled_teeth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='gingival_inflammation',
            field=models.CharField(blank=True, choices=[('slight', 'Slight'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='hard_calc_buildup',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='home_care_effectiveness',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='missing_teeth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='mucogingival_defects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='occlusion',
            field=models.CharField(blank=True, choices=[('class_i', 'Class I'), ('class_ii', 'Class II'), ('class_iii', 'Class III')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='oral_health_age_last_birthday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='periodontal_condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='periodontal_diagnosis',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('gingivitis', 'Gingivitis')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='periodontitis',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('early', 'Early'), ('moderate', 'Moderate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='soft_plaque_buildup',
            field=models.CharField(blank=True, choices=[('slight', 'Slight'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='soft_tissue_floor_of_mouth',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='soft_tissue_lips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='soft_tissue_neck_nodes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='soft_tissue_palate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='soft_tissue_tongue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='stains',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='teeth_present',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='total_dmf_teeth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DentalFormTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveIntegerField(help_text='FDI notation: 11-48 permanent, 51-85 primary')),
                ('tooth_type', models.CharField(choices=[('permanent', 'Permanent'), ('primary', 'Primary/Deciduous')], default='permanent', max_length=20)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('decayed', 'Decayed/Caries'), ('filled', 'Filled'), ('missing', 'Missing'), ('extracted', 'Extracted'), ('impacted', 'Impacted'), ('root_canal', 'Root Canal'), ('crowned', 'Crowned'), ('bridge', 'Bridge'), ('bridge_pontic', 'Bridge Pontic'), ('implant', 'Implant'), ('fractured', 'Fractured'), ('unerupted', 'Unerupted'), ('partially_erupted', 'Partially Erupted'), ('sealant', 'Sealant'), ('veneer', 'Veneer'), ('temporary', 'Temporary Filling'), ('root_fragment', 'Root Fragment'), ('anomaly', 'Anomaly'), ('other', 'Other')], default='healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dental_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart', to='health_forms_services.dentalhealthform')),
            ],
            options={
                'ordering': ['tooth_number'],
                'unique_together': {('dental_form', 'tooth_number')},
            },
        ),
        migrations.CreateModel(
            name='DentalFormToothSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('mesial', 'Mesial (M)'), ('distal', 'Distal (D)'), ('buccal', 'Buccal/Facial (B/F)'), ('lingual', 'Lingual/Palatal (L/P)'), ('occlusal', 'Occlusal (O)')], max_length=20)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('decayed', 'Decayed/Caries'), ('filled', 'Filled'), ('filled_with_caries', 'Filled with Caries'), ('sealant', 'Sealant'), ('fracture', 'Fracture')], default='healthy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='health_forms_services.dentalformtooth')),
            ],
            options={
                'ordering': ['surface'],
                'unique_together': {('tooth', 'surface')},
            },
        ),
    ]
