# Generated by Django 5.2 on 2026-06-24 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0008_alter_dentalhealthform_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentalhealthform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dental Services Form', 'verbose_name_plural': 'Dental Services Forms'},
        ),
        migrations.AlterModelOptions(
            name='dentalservicesrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dental Health Form', 'verbose_name_plural': 'Dental Health Forms'},
        ),
        migrations.AddField(
            model_name='dentalhealthform',
            name='examined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_dental_health_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
