# Generated by Django 5.2 on 2026-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0009_dentalhealthform_examined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalhealthform',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('guest', 'Guest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff'), ('doctor', 'Doctor'), ('employee', 'Employee'), ('guest', 'Guest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientchart',
            name='designation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('guest', 'Guest')], max_length=20),
        ),
    ]
