# Generated by Django 5.2.4 on 2026-02-09 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0009_dentalservicesrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('certificate_date', models.DateField(blank=True, help_text='Date printed on certificate', null=True)),
                ('patient_name', models.CharField(help_text='Complete Name', max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('consultation_date', models.DateField(blank=True, help_text='Date patient came in for consult', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnosis / medical findings')),
                ('remarks_recommendations', models.TextField(blank=True, help_text='Remarks and recommendations')),
                ('physician_name', models.CharField(blank=True, max_length=200)),
                ('license_no', models.CharField(blank=True, max_length=100)),
                ('ptr_no', models.CharField(blank=True, max_length=100, verbose_name='PTR No.')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_medical_certificates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Certificate',
                'verbose_name_plural': 'Medical Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, help_text='Date of prescription', null=True)),
                ('prescription_body', models.TextField(blank=True, help_text='Prescription details — medications, dosage, instructions')),
                ('physician_name', models.CharField(blank=True, max_length=200)),
                ('license_no', models.CharField(blank=True, max_length=100)),
                ('ptr_no', models.CharField(blank=True, max_length=100, verbose_name='PTR No.')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Drug name / brand', max_length=300)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500mg', max_length=200)),
                ('frequency', models.CharField(blank=True, help_text='e.g. 3x a day', max_length=200)),
                ('duration', models.CharField(blank=True, help_text='e.g. 7 days', max_length=200)),
                ('quantity', models.CharField(blank=True, help_text='e.g. #21', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='health_forms_services.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'ordering': ['id'],
            },
        ),
    ]
