# Generated by Django 5.2

from django.db import migrations, models


def forwards_guest_to_walk_in(apps, schema_editor):
    for model_name in ('HealthProfileForm', 'DentalHealthForm', 'PatientChart'):
        Model = apps.get_model('health_forms_services', model_name)
        Model.objects.filter(designation='guest').update(designation='walk_in')


def backwards_walk_in_to_guest(apps, schema_editor):
    for model_name in ('HealthProfileForm', 'DentalHealthForm', 'PatientChart'):
        Model = apps.get_model('health_forms_services', model_name)
        Model.objects.filter(designation='walk_in').update(designation='guest')


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0010_patient_category_and_guest_designation'),
    ]

    operations = [
        migrations.RunPython(forwards_guest_to_walk_in, backwards_walk_in_to_guest),
        migrations.AlterField(
            model_name='dentalhealthform',
            name='designation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                    ('walk_in', 'Walk-in'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='designation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('staff', 'Staff'),
                    ('doctor', 'Doctor'),
                    ('employee', 'Employee'),
                    ('walk_in', 'Walk-in'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='patientchart',
            name='designation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                    ('walk_in', 'Walk-in'),
                ],
                max_length=20,
            ),
        ),
    ]
