# Generated by Django 5.2

from django.db import migrations, models


def forwards_clear_walk_in_designation(apps, schema_editor):
    for model_name in ('HealthProfileForm', 'DentalHealthForm', 'PatientChart'):
        Model = apps.get_model('health_forms_services', model_name)
        Model.objects.filter(designation__in=['guest', 'walk_in']).update(designation='')


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0011_rename_guest_to_walk_in'),
    ]

    operations = [
        migrations.RunPython(forwards_clear_walk_in_designation, backwards_noop),
        migrations.AlterField(
            model_name='dentalhealthform',
            name='designation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='healthprofileform',
            name='designation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('staff', 'Staff'),
                    ('doctor', 'Doctor'),
                    ('employee', 'Employee'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='patientchart',
            name='designation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('employee', 'Employee'),
                ],
                max_length=20,
            ),
        ),
    ]
