# Generated by Django 5.2 on 2026-08-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0013_alter_dentalhealthform_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofileform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
