# Generated by Django 5.2 on 2026-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_forms_services', '0014_healthprofileform_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientchart',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientchart',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientchart',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientchart',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
